import json
from typing import Any, List, Optional, Union

from langchain.embeddings import logger
from langchain_core.callbacks import CallbackManagerForLLMRun
from langchain_core.language_models.llms import LLM
from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    FunctionMessage,
    HumanMessage,
    SystemMessage,
)
from pydantic import Field

from langchain_community.llms.utils import enforce_stop_tokens
from core import config as env
from . import _convert_message_to_dict

HEADERS = {"Content-Type": "application/json", "Authorization": f"Bearer {env.DOUBAO_API_KEY}"}
DEFAULT_TIMEOUT = 30


class DouBao(LLM):
    """DouBao LLM service."""

    model_name: str = Field(default=env.DOUBAO_PRO_32K_MODEL, alias="model")
    api_key: str = env.DOUBAO_API_KEY
    endpoint_url: str = env.DOUBAO_API_ENDPOINT
    """Endpoint URL to use."""
    model_kwargs: Optional[dict] = None
    """Keyword arguments to pass to the model."""
    max_tokens: int = 20000
    """Max token allowed to pass to the model."""
    temperature: float = 0.5
    """LLM model temperature from 0 to 10."""
    top_p: float = 0.7
    """Top P for nucleus sampling from 0 to 1"""
    prefix_messages: List[BaseMessage] = Field(default_factory=list)
    """Series of messages for Chat input."""
    streaming: bool = False
    """Whether to stream the results or not."""
    http_client: Union[Any, None] = None
    timeout: int = DEFAULT_TIMEOUT

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.model_name = kwargs.get("model", env.DOUBAO_PRO_32K_MODEL)
        self.api_key = kwargs.get("api_key", env.DOUBAO_API_KEY)
        self.endpoint_url = kwargs.get("endpoint_url", env.DOUBAO_API_ENDPOINT)
        self.max_tokens = kwargs.get("max_tokens", 20000)
        self.temperature = kwargs.get("temperature", 0.5)
        self.top_p = kwargs.get("top_p", 0.7)
        self.prefix_messages = kwargs.get("prefix_messages", [])
        self.streaming = kwargs.get("streaming", False)
        self.model_kwargs = kwargs.get("model_kwargs", {})
        self.http_client = kwargs.get("http_client")
        self.timeout = kwargs.get("timeout", DEFAULT_TIMEOUT)

    @property
    def _llm_type(self) -> str:
        return "doubao"

    @property
    def _invocation_params(self) -> dict:
        """Get the parameters used to invoke the model."""
        params = {
            "model": self.model_name,
            # "temperature": self.temperature,
            # "top_p": self.top_p,
            # "stream": self.streaming,
        }
        return {**params, **(self.model_kwargs or {})}

    @property
    def client(self) -> Any:
        import httpx
        return httpx.Client(timeout=self.timeout)

    def _get_payload(self, prompt: str) -> dict:
        params = self._invocation_params
        messages = self.prefix_messages + [HumanMessage(content=prompt)]
        params.update(
            {
                "messages": [_convert_message_to_dict(m) for m in messages],
            }
        )
        return params

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        """Call out to a DouBao LLM inference endpoint.

        Args:
            prompt: The prompt to pass into the model.
            stop: Optional list of stop words to use when generating.

        Returns:
            The string generated by the model.

        Example:
            .. code-block:: python

                response = chatglm_llm.invoke("Who are you?")
        """
        import httpx

        payload = self._get_payload(prompt)
        logger.debug(f"DouBao payload: {payload}")

        try:
            response = self.client.post(
                self.endpoint_url, headers=HEADERS, json=payload,
                timeout=self.timeout  # Ensure the timeout is passed to the request
            )
        except httpx.NetworkError as e:
            raise ValueError(f"Error raised by inference endpoint: {e}")

        logger.debug(f"DouBao response: {response}")

        if response.status_code != 200:
            raise ValueError(f"Failed with response: {response}")

        try:
            parsed_response = response.json()

            if isinstance(parsed_response, dict):
                content_keys = "choices"
                if content_keys in parsed_response:
                    choices = parsed_response[content_keys]
                    if len(choices):
                        text = choices[0]["message"]["content"]
                else:
                    raise ValueError(f"No content in response : {parsed_response}")
            else:
                raise ValueError(f"Unexpected response type: {parsed_response}")

        except json.JSONDecodeError as e:
            raise ValueError(
                f"Error raised during decoding response from inference endpoint: {e}."
                f"\nResponse: {response.text}"
            )

        if stop is not None:
            text = enforce_stop_tokens(text, stop)

        return text